"""Criando tudo no dev

Revision ID: 9fb0c452009f
Revises: 
Create Date: 2025-10-07 20:29:21.816719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb0c452009f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('signatureStatus', sa.Enum('active', 'inactive', name='usersignaturestatusenum', schema='dev'), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userroleenum', schema='dev'), nullable=True),
    sa.Column('notifications', sa.Enum('yes', 'no', name='usernotificationpreferenceenum', schema='dev'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dev'
    )
    op.create_index(op.f('ix_dev_users_email'), 'users', ['email'], unique=True, schema='dev')
    op.create_index(op.f('ix_dev_users_name'), 'users', ['name'], unique=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_users_name'), table_name='users', schema='dev')
    op.drop_index(op.f('ix_dev_users_email'), table_name='users', schema='dev')
    op.drop_table('users', schema='dev')
    # ### end Alembic commands ###
