-- 1. Primeiro criamos a tabela com todas as colunas e tipos específicos
CREATE TABLE IF NOT EXISTS silver.google_api_data (
    id SERIAL PRIMARY KEY,
    data_medicao TIMESTAMP,
    regiao VARCHAR(2),
    
    aqi_universal INTEGER,
    codigo_universal VARCHAR(4),
    cor_vermelho_universal DECIMAL(9,8),
    cor_azul_universal DECIMAL(9,8),
    cor_verde_universal DECIMAL(9,8),
    categoria_universal VARCHAR(50),
    valor_display_universal INTEGER,
    nome_display_universal VARCHAR(20),
    poluente_dominante_universal VARCHAR(10),
    
    aqi_br INTEGER,
    codigo_br VARCHAR(20),
    cor_br DECIMAL(2,1),
    categoria_br VARCHAR(20),
    valor_display_br INTEGER,
    nome_display_br VARCHAR(20),
    poluente_dominante_br VARCHAR(10),
    
    co_code VARCHAR(10),
    co_nome VARCHAR(20),
    co_display_nome VARCHAR(10),
    co_concentracao_unidade VARCHAR(30),
    co_valor NUMERIC(10,6),
    
    no2_code VARCHAR(10),
    no2_nome VARCHAR(50),
    no2_display_nome VARCHAR(10),
    no2_concentracao_unidade VARCHAR(30),
    no2_valor NUMERIC(10,6),
    
    o3_code VARCHAR(10),
    o3_nome VARCHAR(50),
    o3_display_nome VARCHAR(10),
    o3_concentracao_unidade VARCHAR(30),
    o3_valor NUMERIC(10,6),
    
    pm10_code VARCHAR(10),
    pm10_nome VARCHAR(50),
    pm10_display_nome VARCHAR(10),
    pm10_concentracao_unidade VARCHAR(30),
    pm10_valor NUMERIC(10,6),
    
    pm25_code VARCHAR(10),
    pm25_nome VARCHAR(50),
    pm25_display_nome VARCHAR(10),
    pm25_concentracao_unidade VARCHAR(30),
    pm25_valor NUMERIC(10,6),
    
    so2_code VARCHAR(10),
    so2_nome VARCHAR(50),
    so2_display_nome VARCHAR(10),
    so2_concentracao_unidade VARCHAR(30),
    so2_valor NUMERIC(10,6)
);


INSERT INTO silver.google_api_data (
    data_medicao,
    regiao,
    aqi_universal,
    codigo_universal,
    cor_vermelho_universal,
    cor_azul_universal,
    cor_verde_universal,
    categoria_universal,
    valor_display_universal,
    nome_display_universal,
    poluente_dominante_universal,
    aqi_br,
    codigo_br,
    cor_br,
    categoria_br,
    valor_display_br,
    nome_display_br,
    poluente_dominante_br,
    co_code,
    co_nome,
    co_display_nome,
    co_concentracao_unidade,
    co_valor,
    no2_code,
    no2_nome,
    no2_display_nome,
    no2_concentracao_unidade,
    no2_valor,
    o3_code,
    o3_nome,
    o3_display_nome,
    o3_concentracao_unidade,
    o3_valor,
    pm10_code,
    pm10_nome,
    pm10_display_nome,
    pm10_concentracao_unidade,
    pm10_valor,
    pm25_code,
    pm25_nome,
    pm25_display_nome,
    pm25_concentracao_unidade,
    pm25_valor,
    so2_code,
    so2_nome,
    so2_display_nome,
    so2_concentracao_unidade,
    so2_valor
)
SELECT 
    (data->>'dateTime')::TIMESTAMP AS data_medicao,
    data->>'regionCode' AS regiao,
    
    (data#>>'{indexes,0,aqi}')::INTEGER AS aqi_universal,
    data#>>'{indexes,0,code}' AS codigo_universal,
    (data#>>'{indexes,0,color,red}')::DECIMAL(9,8) AS cor_vermelho_universal,
    (data#>>'{indexes,0,color,blue}')::DECIMAL(9,8) AS cor_azul_universal,
    (data#>>'{indexes,0,color,green}')::DECIMAL(9,8) AS cor_verde_universal,
    data#>>'{indexes,0,category}' AS categoria_universal,
    (data#>>'{indexes,0,aqiDisplay}')::INTEGER AS valor_display_universal,
    data#>>'{indexes,0,displayName}' AS nome_display_universal,
    data#>>'{indexes,0,dominantPollutant}' AS poluente_dominante_universal,
    
    (data#>>'{indexes,1,aqi}')::INTEGER AS aqi_br,
    data#>>'{indexes,1,code}' AS codigo_br,
    (data#>>'{indexes,1,color,green}')::DECIMAL(2,1) AS cor_br,
    data#>>'{indexes,1,category}' AS categoria_br,
    (data#>>'{indexes,1,aqiDisplay}')::INTEGER AS valor_display_br,
    data#>>'{indexes,1,displayName}' AS nome_display_br,
    data#>>'{indexes,1,dominantPollutant}' AS poluente_dominante_br,

    data#>>'{pollutants,0,code}' AS co_code,
    data#>>'{pollutants,0,fullName}' AS co_nome,
    data#>>'{pollutants,0,displayName}' AS co_display_nome,
    data#>>'{pollutants,0,concentration,units}' AS co_concentracao_unidade,
    (data#>>'{pollutants,0,concentration,value}')::NUMERIC(10,6) AS co_valor,

    data#>>'{pollutants,1,code}' AS no2_code,
    data#>>'{pollutants,1,fullName}' AS no2_nome,
    data#>>'{pollutants,1,displayName}' AS no2_display_nome,
    data#>>'{pollutants,1,concentration,units}' AS no2_concentracao_unidade,
    (data#>>'{pollutants,1,concentration,value}')::NUMERIC(10,6) AS no2_valor,

    data#>>'{pollutants,2,code}' AS o3_code,
    data#>>'{pollutants,2,fullName}' AS o3_nome,
    data#>>'{pollutants,2,displayName}' AS o3_display_nome,
    data#>>'{pollutants,2,concentration,units}' AS o3_concentracao_unidade,
    (data#>>'{pollutants,2,concentration,value}')::NUMERIC(10,6) AS o3_valor,

    data#>>'{pollutants,3,code}' AS pm10_code,
    data#>>'{pollutants,3,fullName}' AS pm10_nome,
    data#>>'{pollutants,3,displayName}' AS pm10_display_nome,
    data#>>'{pollutants,3,concentration,units}' AS pm10_concentracao_unidade,
    (data#>>'{pollutants,3,concentration,value}')::NUMERIC(10,6) AS pm10_valor,

    data#>>'{pollutants,4,code}' AS pm25_code,
    data#>>'{pollutants,4,fullName}' AS pm25_nome,
    data#>>'{pollutants,4,displayName}' AS pm25_display_nome,
    data#>>'{pollutants,4,concentration,units}' AS pm25_concentracao_unidade,
    (data#>>'{pollutants,4,concentration,value}')::NUMERIC(10,6) AS pm25_valor,

    data#>>'{pollutants,5,code}' AS so2_code,
    data#>>'{pollutants,5,fullName}' AS so2_nome,
    data#>>'{pollutants,5,displayName}' AS so2_display_nome,
    data#>>'{pollutants,5,concentration,units}' AS so2_concentracao_unidade,
    (data#>>'{pollutants,5,concentration,value}')::NUMERIC(10,6) AS so2_valor
FROM 
    bronze.google_api_data;