name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuração do Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Instalação das dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Criação do arquivo .env com as variáveis necessárias
    - name: Create .env file
      run: |
        echo "API_KEY=mocked_api_key" >> .env
        echo "LATITUDE=37.7749" >> .env
        echo "LONGITUDE=-122.4194" >> .env

    # Execução dos testes com pytest e geração de relatório de cobertura
    - name: Run Tests with pytest
      run: |
        pytest --cov=pipe --cov-report=term-missing
